name: My Workflow

on:
  pull_request:
    branches:
      - main
      - master
    types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract PR Comment
        id: pr_comment
        run: |
          TAG=$(echo "$PULL_REQUEST_BODY" | grep -Po '(?<=tag: )v\d+\.\d+\.\d+')
          if [ -n "$TAG" ]; then
            gh release create $TAG --generate-notes
          fi
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
          PULL_REQUEST_BODY: "${{ github.event.pull_request.body }}"
